// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  Map<String, Uint8List> dco_decode_Map_String_list_prim_u_8_strict_None(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AdaptorSignatureResult dco_decode_adaptor_signature_result(dynamic raw);

  @protected
  InternalTransactionResult dco_decode_box_autoadd_internal_transaction_result(
    dynamic raw,
  );

  @protected
  DummyTxResult dco_decode_dummy_tx_result(dynamic raw);

  @protected
  InternalTransactionResult dco_decode_internal_transaction_result(dynamic raw);

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw);

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<(String, Uint8List)> dco_decode_list_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  List<SecretShare> dco_decode_list_secret_share(dynamic raw);

  @protected
  List<VerifiableSecretShareResult>
  dco_decode_list_verifiable_secret_share_result(dynamic raw);

  @protected
  NodeTxPairResult dco_decode_node_tx_pair_result(dynamic raw);

  @protected
  InternalTransactionResult?
  dco_decode_opt_box_autoadd_internal_transaction_result(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  (String, Uint8List) dco_decode_record_string_list_prim_u_8_strict(
    dynamic raw,
  );

  @protected
  RefundTxTrioResult dco_decode_refund_tx_trio_result(dynamic raw);

  @protected
  SecretShare dco_decode_secret_share(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  VerifiableSecretShareResult dco_decode_verifiable_secret_share_result(
    dynamic raw,
  );

  @protected
  Map<String, Uint8List> sse_decode_Map_String_list_prim_u_8_strict_None(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AdaptorSignatureResult sse_decode_adaptor_signature_result(
    SseDeserializer deserializer,
  );

  @protected
  InternalTransactionResult sse_decode_box_autoadd_internal_transaction_result(
    SseDeserializer deserializer,
  );

  @protected
  DummyTxResult sse_decode_dummy_tx_result(SseDeserializer deserializer);

  @protected
  InternalTransactionResult sse_decode_internal_transaction_result(
    SseDeserializer deserializer,
  );

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer);

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<(String, Uint8List)> sse_decode_list_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  List<SecretShare> sse_decode_list_secret_share(SseDeserializer deserializer);

  @protected
  List<VerifiableSecretShareResult>
  sse_decode_list_verifiable_secret_share_result(SseDeserializer deserializer);

  @protected
  NodeTxPairResult sse_decode_node_tx_pair_result(SseDeserializer deserializer);

  @protected
  InternalTransactionResult?
  sse_decode_opt_box_autoadd_internal_transaction_result(
    SseDeserializer deserializer,
  );

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  (String, Uint8List) sse_decode_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  );

  @protected
  RefundTxTrioResult sse_decode_refund_tx_trio_result(
    SseDeserializer deserializer,
  );

  @protected
  SecretShare sse_decode_secret_share(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  VerifiableSecretShareResult sse_decode_verifiable_secret_share_result(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_Map_String_list_prim_u_8_strict_None(
    Map<String, Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_adaptor_signature_result(
    AdaptorSignatureResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_internal_transaction_result(
    InternalTransactionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_dummy_tx_result(DummyTxResult self, SseSerializer serializer);

  @protected
  void sse_encode_internal_transaction_result(
    InternalTransactionResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_record_string_list_prim_u_8_strict(
    List<(String, Uint8List)> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_secret_share(
    List<SecretShare> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_verifiable_secret_share_result(
    List<VerifiableSecretShareResult> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_node_tx_pair_result(
    NodeTxPairResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_internal_transaction_result(
    InternalTransactionResult? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_record_string_list_prim_u_8_strict(
    (String, Uint8List) self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_refund_tx_trio_result(
    RefundTxTrioResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_secret_share(SecretShare self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_verifiable_secret_share_result(
    VerifiableSecretShareResult self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
