// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -694967745;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'rust_lib_spark_flutter',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<Uint8List> crateApiSimpleAggregateFrost({
    required List<int> msg,
    required Map<String, Uint8List> statechainCommitmentsBytes,
    required List<int> selfCommitmentBytes,
    required Map<String, Uint8List> statechainSignatures,
    required List<int> selfSignature,
    required Map<String, Uint8List> statechainPublicKeys,
    required List<int> selfPublicKey,
    required List<int> verifyingKey,
    Uint8List? adaptorPublicKey,
  });

  Future<Uint8List> crateApiSimpleApplyAdaptorToSignature({
    required List<int> pubKey,
    required List<int> hash,
    required List<int> signature,
    required List<int> adaptorPrivateKey,
  });

  Future<Uint8List> crateApiSimpleComputeMultiInputSighash({
    required List<int> txBytes,
    required int inputIndex,
    required List<Uint8List> prevOutScripts,
    required Uint64List prevOutValues,
  });

  Future<NodeTxPairResult> crateApiSimpleConstructNodeTxPair({
    required List<int> parentTxBytes,
    required int vout,
    required String address,
    required int sequence,
    required int directSequence,
    required BigInt feeSats,
  });

  Future<RefundTxTrioResult> crateApiSimpleConstructRefundTxTrio({
    required List<int> cpfpNodeTxBytes,
    Uint8List? directNodeTxBytes,
    required int vout,
    required List<int> receivingPubkey,
    required String network,
    required int sequence,
    required int directSequence,
    required BigInt feeSats,
  });

  Future<DummyTxResult> crateApiSimpleCreateDummyTx({
    required String address,
    required BigInt amountSats,
  });

  Future<Uint8List> crateApiSimpleDecryptEcies({
    required List<int> encryptedMsg,
    required List<int> privateKeyBytes,
  });

  Future<Uint8List> crateApiSimpleEncryptEcies({
    required List<int> msg,
    required List<int> publicKeyBytes,
  });

  Future<AdaptorSignatureResult> crateApiSimpleGenerateAdaptorFromSignature({
    required List<int> signatureBytes,
  });

  Future<Uint8List> crateApiSimpleGenerateSignatureFromExistingAdaptor({
    required List<int> signatureBytes,
    required List<int> adaptorPrivateKeyBytes,
  });

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<Uint8List> crateApiSimpleRecoverSecret({
    required List<SecretShare> shares,
  });

  Future<Uint8List> crateApiSimpleSignFrost({
    required List<int> msg,
    required List<int> keyPackageBytes,
    required List<int> nonceBytes,
    required List<int> selfCommitmentBytes,
    required Map<String, Uint8List> statechainCommitmentsBytes,
    Uint8List? adaptorPublicKey,
  });

  Future<List<VerifiableSecretShareResult>>
  crateApiSimpleSplitSecretWithProofs({
    required List<int> secret,
    required BigInt threshold,
    required BigInt numShares,
  });

  Future<void> crateApiSimpleValidateAdaptorSignature({
    required List<int> pubKey,
    required List<int> hash,
    required List<int> signature,
    required List<int> adaptorPubKey,
  });

  Future<void> crateApiSimpleValidateShare({
    required List<int> share,
    required int index,
    required BigInt threshold,
    required List<Uint8List> proofs,
  });
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<Uint8List> crateApiSimpleAggregateFrost({
    required List<int> msg,
    required Map<String, Uint8List> statechainCommitmentsBytes,
    required List<int> selfCommitmentBytes,
    required Map<String, Uint8List> statechainSignatures,
    required List<int> selfSignature,
    required Map<String, Uint8List> statechainPublicKeys,
    required List<int> selfPublicKey,
    required List<int> verifyingKey,
    Uint8List? adaptorPublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(msg, serializer);
          sse_encode_Map_String_list_prim_u_8_strict_None(
            statechainCommitmentsBytes,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(selfCommitmentBytes, serializer);
          sse_encode_Map_String_list_prim_u_8_strict_None(
            statechainSignatures,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(selfSignature, serializer);
          sse_encode_Map_String_list_prim_u_8_strict_None(
            statechainPublicKeys,
            serializer,
          );
          sse_encode_list_prim_u_8_loose(selfPublicKey, serializer);
          sse_encode_list_prim_u_8_loose(verifyingKey, serializer);
          sse_encode_opt_list_prim_u_8_strict(adaptorPublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleAggregateFrostConstMeta,
        argValues: [
          msg,
          statechainCommitmentsBytes,
          selfCommitmentBytes,
          statechainSignatures,
          selfSignature,
          statechainPublicKeys,
          selfPublicKey,
          verifyingKey,
          adaptorPublicKey,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleAggregateFrostConstMeta =>
      const TaskConstMeta(
        debugName: "aggregate_frost",
        argNames: [
          "msg",
          "statechainCommitmentsBytes",
          "selfCommitmentBytes",
          "statechainSignatures",
          "selfSignature",
          "statechainPublicKeys",
          "selfPublicKey",
          "verifyingKey",
          "adaptorPublicKey",
        ],
      );

  @override
  Future<Uint8List> crateApiSimpleApplyAdaptorToSignature({
    required List<int> pubKey,
    required List<int> hash,
    required List<int> signature,
    required List<int> adaptorPrivateKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pubKey, serializer);
          sse_encode_list_prim_u_8_loose(hash, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          sse_encode_list_prim_u_8_loose(adaptorPrivateKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleApplyAdaptorToSignatureConstMeta,
        argValues: [pubKey, hash, signature, adaptorPrivateKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleApplyAdaptorToSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "apply_adaptor_to_signature",
        argNames: ["pubKey", "hash", "signature", "adaptorPrivateKey"],
      );

  @override
  Future<Uint8List> crateApiSimpleComputeMultiInputSighash({
    required List<int> txBytes,
    required int inputIndex,
    required List<Uint8List> prevOutScripts,
    required Uint64List prevOutValues,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(txBytes, serializer);
          sse_encode_u_32(inputIndex, serializer);
          sse_encode_list_list_prim_u_8_strict(prevOutScripts, serializer);
          sse_encode_list_prim_u_64_strict(prevOutValues, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleComputeMultiInputSighashConstMeta,
        argValues: [txBytes, inputIndex, prevOutScripts, prevOutValues],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleComputeMultiInputSighashConstMeta =>
      const TaskConstMeta(
        debugName: "compute_multi_input_sighash",
        argNames: ["txBytes", "inputIndex", "prevOutScripts", "prevOutValues"],
      );

  @override
  Future<NodeTxPairResult> crateApiSimpleConstructNodeTxPair({
    required List<int> parentTxBytes,
    required int vout,
    required String address,
    required int sequence,
    required int directSequence,
    required BigInt feeSats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(parentTxBytes, serializer);
          sse_encode_u_32(vout, serializer);
          sse_encode_String(address, serializer);
          sse_encode_u_32(sequence, serializer);
          sse_encode_u_32(directSequence, serializer);
          sse_encode_u_64(feeSats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_node_tx_pair_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConstructNodeTxPairConstMeta,
        argValues: [
          parentTxBytes,
          vout,
          address,
          sequence,
          directSequence,
          feeSats,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConstructNodeTxPairConstMeta =>
      const TaskConstMeta(
        debugName: "construct_node_tx_pair",
        argNames: [
          "parentTxBytes",
          "vout",
          "address",
          "sequence",
          "directSequence",
          "feeSats",
        ],
      );

  @override
  Future<RefundTxTrioResult> crateApiSimpleConstructRefundTxTrio({
    required List<int> cpfpNodeTxBytes,
    Uint8List? directNodeTxBytes,
    required int vout,
    required List<int> receivingPubkey,
    required String network,
    required int sequence,
    required int directSequence,
    required BigInt feeSats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(cpfpNodeTxBytes, serializer);
          sse_encode_opt_list_prim_u_8_strict(directNodeTxBytes, serializer);
          sse_encode_u_32(vout, serializer);
          sse_encode_list_prim_u_8_loose(receivingPubkey, serializer);
          sse_encode_String(network, serializer);
          sse_encode_u_32(sequence, serializer);
          sse_encode_u_32(directSequence, serializer);
          sse_encode_u_64(feeSats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_refund_tx_trio_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleConstructRefundTxTrioConstMeta,
        argValues: [
          cpfpNodeTxBytes,
          directNodeTxBytes,
          vout,
          receivingPubkey,
          network,
          sequence,
          directSequence,
          feeSats,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleConstructRefundTxTrioConstMeta =>
      const TaskConstMeta(
        debugName: "construct_refund_tx_trio",
        argNames: [
          "cpfpNodeTxBytes",
          "directNodeTxBytes",
          "vout",
          "receivingPubkey",
          "network",
          "sequence",
          "directSequence",
          "feeSats",
        ],
      );

  @override
  Future<DummyTxResult> crateApiSimpleCreateDummyTx({
    required String address,
    required BigInt amountSats,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(address, serializer);
          sse_encode_u_64(amountSats, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_dummy_tx_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleCreateDummyTxConstMeta,
        argValues: [address, amountSats],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleCreateDummyTxConstMeta =>
      const TaskConstMeta(
        debugName: "create_dummy_tx",
        argNames: ["address", "amountSats"],
      );

  @override
  Future<Uint8List> crateApiSimpleDecryptEcies({
    required List<int> encryptedMsg,
    required List<int> privateKeyBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(encryptedMsg, serializer);
          sse_encode_list_prim_u_8_loose(privateKeyBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleDecryptEciesConstMeta,
        argValues: [encryptedMsg, privateKeyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleDecryptEciesConstMeta => const TaskConstMeta(
    debugName: "decrypt_ecies",
    argNames: ["encryptedMsg", "privateKeyBytes"],
  );

  @override
  Future<Uint8List> crateApiSimpleEncryptEcies({
    required List<int> msg,
    required List<int> publicKeyBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(msg, serializer);
          sse_encode_list_prim_u_8_loose(publicKeyBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleEncryptEciesConstMeta,
        argValues: [msg, publicKeyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleEncryptEciesConstMeta => const TaskConstMeta(
    debugName: "encrypt_ecies",
    argNames: ["msg", "publicKeyBytes"],
  );

  @override
  Future<AdaptorSignatureResult> crateApiSimpleGenerateAdaptorFromSignature({
    required List<int> signatureBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(signatureBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_adaptor_signature_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGenerateAdaptorFromSignatureConstMeta,
        argValues: [signatureBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGenerateAdaptorFromSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "generate_adaptor_from_signature",
        argNames: ["signatureBytes"],
      );

  @override
  Future<Uint8List> crateApiSimpleGenerateSignatureFromExistingAdaptor({
    required List<int> signatureBytes,
    required List<int> adaptorPrivateKeyBytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(signatureBytes, serializer);
          sse_encode_list_prim_u_8_loose(adaptorPrivateKeyBytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleGenerateSignatureFromExistingAdaptorConstMeta,
        argValues: [signatureBytes, adaptorPrivateKeyBytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta
  get kCrateApiSimpleGenerateSignatureFromExistingAdaptorConstMeta =>
      const TaskConstMeta(
        debugName: "generate_signature_from_existing_adaptor",
        argNames: ["signatureBytes", "adaptorPrivateKeyBytes"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(name, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleGreetConstMeta,
        argValues: [name],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta =>
      const TaskConstMeta(debugName: "greet", argNames: ["name"]);

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<Uint8List> crateApiSimpleRecoverSecret({
    required List<SecretShare> shares,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_secret_share(shares, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleRecoverSecretConstMeta,
        argValues: [shares],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleRecoverSecretConstMeta =>
      const TaskConstMeta(debugName: "recover_secret", argNames: ["shares"]);

  @override
  Future<Uint8List> crateApiSimpleSignFrost({
    required List<int> msg,
    required List<int> keyPackageBytes,
    required List<int> nonceBytes,
    required List<int> selfCommitmentBytes,
    required Map<String, Uint8List> statechainCommitmentsBytes,
    Uint8List? adaptorPublicKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(msg, serializer);
          sse_encode_list_prim_u_8_loose(keyPackageBytes, serializer);
          sse_encode_list_prim_u_8_loose(nonceBytes, serializer);
          sse_encode_list_prim_u_8_loose(selfCommitmentBytes, serializer);
          sse_encode_Map_String_list_prim_u_8_strict_None(
            statechainCommitmentsBytes,
            serializer,
          );
          sse_encode_opt_list_prim_u_8_strict(adaptorPublicKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_prim_u_8_strict,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSignFrostConstMeta,
        argValues: [
          msg,
          keyPackageBytes,
          nonceBytes,
          selfCommitmentBytes,
          statechainCommitmentsBytes,
          adaptorPublicKey,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSignFrostConstMeta => const TaskConstMeta(
    debugName: "sign_frost",
    argNames: [
      "msg",
      "keyPackageBytes",
      "nonceBytes",
      "selfCommitmentBytes",
      "statechainCommitmentsBytes",
      "adaptorPublicKey",
    ],
  );

  @override
  Future<List<VerifiableSecretShareResult>>
  crateApiSimpleSplitSecretWithProofs({
    required List<int> secret,
    required BigInt threshold,
    required BigInt numShares,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(secret, serializer);
          sse_encode_usize(threshold, serializer);
          sse_encode_usize(numShares, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 15,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_list_verifiable_secret_share_result,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleSplitSecretWithProofsConstMeta,
        argValues: [secret, threshold, numShares],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleSplitSecretWithProofsConstMeta =>
      const TaskConstMeta(
        debugName: "split_secret_with_proofs",
        argNames: ["secret", "threshold", "numShares"],
      );

  @override
  Future<void> crateApiSimpleValidateAdaptorSignature({
    required List<int> pubKey,
    required List<int> hash,
    required List<int> signature,
    required List<int> adaptorPubKey,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(pubKey, serializer);
          sse_encode_list_prim_u_8_loose(hash, serializer);
          sse_encode_list_prim_u_8_loose(signature, serializer);
          sse_encode_list_prim_u_8_loose(adaptorPubKey, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 16,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleValidateAdaptorSignatureConstMeta,
        argValues: [pubKey, hash, signature, adaptorPubKey],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleValidateAdaptorSignatureConstMeta =>
      const TaskConstMeta(
        debugName: "validate_adaptor_signature",
        argNames: ["pubKey", "hash", "signature", "adaptorPubKey"],
      );

  @override
  Future<void> crateApiSimpleValidateShare({
    required List<int> share,
    required int index,
    required BigInt threshold,
    required List<Uint8List> proofs,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_list_prim_u_8_loose(share, serializer);
          sse_encode_u_32(index, serializer);
          sse_encode_usize(threshold, serializer);
          sse_encode_list_list_prim_u_8_strict(proofs, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 17,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSimpleValidateShareConstMeta,
        argValues: [share, index, threshold, proofs],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleValidateShareConstMeta =>
      const TaskConstMeta(
        debugName: "validate_share",
        argNames: ["share", "index", "threshold", "proofs"],
      );

  @protected
  Map<String, Uint8List> dco_decode_Map_String_list_prim_u_8_strict_None(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return Map.fromEntries(
      dco_decode_list_record_string_list_prim_u_8_strict(
        raw,
      ).map((e) => MapEntry(e.$1, e.$2)),
    );
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AdaptorSignatureResult dco_decode_adaptor_signature_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return AdaptorSignatureResult(
      part1: dco_decode_list_prim_u_8_strict(arr[0]),
      part2: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  InternalTransactionResult dco_decode_box_autoadd_internal_transaction_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_internal_transaction_result(raw);
  }

  @protected
  DummyTxResult dco_decode_dummy_tx_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return DummyTxResult(
      tx: dco_decode_list_prim_u_8_strict(arr[0]),
      txid: dco_decode_String(arr[1]),
    );
  }

  @protected
  InternalTransactionResult dco_decode_internal_transaction_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return InternalTransactionResult(
      txBytes: dco_decode_list_prim_u_8_strict(arr[0]),
      sighash: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  List<Uint8List> dco_decode_list_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_list_prim_u_8_strict).toList();
  }

  @protected
  Uint64List dco_decode_list_prim_u_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeUint64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<(String, Uint8List)> dco_decode_list_record_string_list_prim_u_8_strict(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_record_string_list_prim_u_8_strict)
        .toList();
  }

  @protected
  List<SecretShare> dco_decode_list_secret_share(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_secret_share).toList();
  }

  @protected
  List<VerifiableSecretShareResult>
  dco_decode_list_verifiable_secret_share_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_verifiable_secret_share_result)
        .toList();
  }

  @protected
  NodeTxPairResult dco_decode_node_tx_pair_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return NodeTxPairResult(
      cpfp: dco_decode_internal_transaction_result(arr[0]),
      direct: dco_decode_internal_transaction_result(arr[1]),
    );
  }

  @protected
  InternalTransactionResult?
  dco_decode_opt_box_autoadd_internal_transaction_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null
        ? null
        : dco_decode_box_autoadd_internal_transaction_result(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (String, Uint8List) dco_decode_record_string_list_prim_u_8_strict(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (dco_decode_String(arr[0]), dco_decode_list_prim_u_8_strict(arr[1]));
  }

  @protected
  RefundTxTrioResult dco_decode_refund_tx_trio_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return RefundTxTrioResult(
      cpfpRefund: dco_decode_internal_transaction_result(arr[0]),
      directRefund: dco_decode_opt_box_autoadd_internal_transaction_result(
        arr[1],
      ),
      directFromCpfpRefund: dco_decode_internal_transaction_result(arr[2]),
    );
  }

  @protected
  SecretShare dco_decode_secret_share(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return SecretShare(
      threshold: dco_decode_usize(arr[0]),
      index: dco_decode_u_32(arr[1]),
      share: dco_decode_list_prim_u_8_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  VerifiableSecretShareResult dco_decode_verifiable_secret_share_result(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return VerifiableSecretShareResult(
      threshold: dco_decode_usize(arr[0]),
      index: dco_decode_u_32(arr[1]),
      share: dco_decode_list_prim_u_8_strict(arr[2]),
      proofs: dco_decode_list_list_prim_u_8_strict(arr[3]),
    );
  }

  @protected
  Map<String, Uint8List> sse_decode_Map_String_list_prim_u_8_strict_None(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_record_string_list_prim_u_8_strict(
      deserializer,
    );
    return Map.fromEntries(inner.map((e) => MapEntry(e.$1, e.$2)));
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AdaptorSignatureResult sse_decode_adaptor_signature_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_part1 = sse_decode_list_prim_u_8_strict(deserializer);
    var var_part2 = sse_decode_list_prim_u_8_strict(deserializer);
    return AdaptorSignatureResult(part1: var_part1, part2: var_part2);
  }

  @protected
  InternalTransactionResult sse_decode_box_autoadd_internal_transaction_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_internal_transaction_result(deserializer));
  }

  @protected
  DummyTxResult sse_decode_dummy_tx_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_tx = sse_decode_list_prim_u_8_strict(deserializer);
    var var_txid = sse_decode_String(deserializer);
    return DummyTxResult(tx: var_tx, txid: var_txid);
  }

  @protected
  InternalTransactionResult sse_decode_internal_transaction_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txBytes = sse_decode_list_prim_u_8_strict(deserializer);
    var var_sighash = sse_decode_list_prim_u_8_strict(deserializer);
    return InternalTransactionResult(
      txBytes: var_txBytes,
      sighash: var_sighash,
    );
  }

  @protected
  List<Uint8List> sse_decode_list_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Uint8List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Uint64List sse_decode_list_prim_u_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<(String, Uint8List)> sse_decode_list_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <(String, Uint8List)>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_record_string_list_prim_u_8_strict(deserializer));
    }
    return ans_;
  }

  @protected
  List<SecretShare> sse_decode_list_secret_share(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SecretShare>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_secret_share(deserializer));
    }
    return ans_;
  }

  @protected
  List<VerifiableSecretShareResult>
  sse_decode_list_verifiable_secret_share_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <VerifiableSecretShareResult>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_verifiable_secret_share_result(deserializer));
    }
    return ans_;
  }

  @protected
  NodeTxPairResult sse_decode_node_tx_pair_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cpfp = sse_decode_internal_transaction_result(deserializer);
    var var_direct = sse_decode_internal_transaction_result(deserializer);
    return NodeTxPairResult(cpfp: var_cpfp, direct: var_direct);
  }

  @protected
  InternalTransactionResult?
  sse_decode_opt_box_autoadd_internal_transaction_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_internal_transaction_result(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (String, Uint8List) sse_decode_record_string_list_prim_u_8_strict(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 = sse_decode_String(deserializer);
    var var_field1 = sse_decode_list_prim_u_8_strict(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  RefundTxTrioResult sse_decode_refund_tx_trio_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_cpfpRefund = sse_decode_internal_transaction_result(deserializer);
    var var_directRefund =
        sse_decode_opt_box_autoadd_internal_transaction_result(deserializer);
    var var_directFromCpfpRefund = sse_decode_internal_transaction_result(
      deserializer,
    );
    return RefundTxTrioResult(
      cpfpRefund: var_cpfpRefund,
      directRefund: var_directRefund,
      directFromCpfpRefund: var_directFromCpfpRefund,
    );
  }

  @protected
  SecretShare sse_decode_secret_share(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threshold = sse_decode_usize(deserializer);
    var var_index = sse_decode_u_32(deserializer);
    var var_share = sse_decode_list_prim_u_8_strict(deserializer);
    return SecretShare(
      threshold: var_threshold,
      index: var_index,
      share: var_share,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  VerifiableSecretShareResult sse_decode_verifiable_secret_share_result(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_threshold = sse_decode_usize(deserializer);
    var var_index = sse_decode_u_32(deserializer);
    var var_share = sse_decode_list_prim_u_8_strict(deserializer);
    var var_proofs = sse_decode_list_list_prim_u_8_strict(deserializer);
    return VerifiableSecretShareResult(
      threshold: var_threshold,
      index: var_index,
      share: var_share,
      proofs: var_proofs,
    );
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  void sse_encode_Map_String_list_prim_u_8_strict_None(
    Map<String, Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_record_string_list_prim_u_8_strict(
      self.entries.map((e) => (e.key, e.value)).toList(),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_adaptor_signature_result(
    AdaptorSignatureResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.part1, serializer);
    sse_encode_list_prim_u_8_strict(self.part2, serializer);
  }

  @protected
  void sse_encode_box_autoadd_internal_transaction_result(
    InternalTransactionResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_transaction_result(self, serializer);
  }

  @protected
  void sse_encode_dummy_tx_result(
    DummyTxResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.tx, serializer);
    sse_encode_String(self.txid, serializer);
  }

  @protected
  void sse_encode_internal_transaction_result(
    InternalTransactionResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(self.txBytes, serializer);
    sse_encode_list_prim_u_8_strict(self.sighash, serializer);
  }

  @protected
  void sse_encode_list_list_prim_u_8_strict(
    List<Uint8List> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_64_strict(
    Uint64List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
    List<int> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(
      self is Uint8List ? self : Uint8List.fromList(self),
    );
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_record_string_list_prim_u_8_strict(
    List<(String, Uint8List)> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_record_string_list_prim_u_8_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_secret_share(
    List<SecretShare> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_secret_share(item, serializer);
    }
  }

  @protected
  void sse_encode_list_verifiable_secret_share_result(
    List<VerifiableSecretShareResult> self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_verifiable_secret_share_result(item, serializer);
    }
  }

  @protected
  void sse_encode_node_tx_pair_result(
    NodeTxPairResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_transaction_result(self.cpfp, serializer);
    sse_encode_internal_transaction_result(self.direct, serializer);
  }

  @protected
  void sse_encode_opt_box_autoadd_internal_transaction_result(
    InternalTransactionResult? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_internal_transaction_result(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void sse_encode_record_string_list_prim_u_8_strict(
    (String, Uint8List) self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.$1, serializer);
    sse_encode_list_prim_u_8_strict(self.$2, serializer);
  }

  @protected
  void sse_encode_refund_tx_trio_result(
    RefundTxTrioResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_internal_transaction_result(self.cpfpRefund, serializer);
    sse_encode_opt_box_autoadd_internal_transaction_result(
      self.directRefund,
      serializer,
    );
    sse_encode_internal_transaction_result(
      self.directFromCpfpRefund,
      serializer,
    );
  }

  @protected
  void sse_encode_secret_share(SecretShare self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.threshold, serializer);
    sse_encode_u_32(self.index, serializer);
    sse_encode_list_prim_u_8_strict(self.share, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_verifiable_secret_share_result(
    VerifiableSecretShareResult self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.threshold, serializer);
    sse_encode_u_32(self.index, serializer);
    sse_encode_list_prim_u_8_strict(self.share, serializer);
    sse_encode_list_list_prim_u_8_strict(self.proofs, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }
}
