package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.Log;

import io.flutter.embedding.engine.FlutterEngine;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  private static final String TAG = "GeneratedPluginRegistrant";
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    try {
      flutterEngine.getPlugins().add(new com.visionflutter.biometric_signature.BiometricSignaturePlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin biometric_signature, com.visionflutter.biometric_signature.BiometricSignaturePlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.bip32_key_derivation.Bip32KeyDerivationPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin bip32_key_derivation, com.example.bip32_key_derivation.Bip32KeyDerivationPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new dev.flutter.plugins.integration_test.IntegrationTestPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin integration_test, dev.flutter.plugins.integration_test.IntegrationTestPlugin", e);
    }
    try {
      flutterEngine.getPlugins().add(new com.example.secp256k1_ffi.Secp256k1FfiPlugin());
    } catch (Exception e) {
      Log.e(TAG, "Error registering plugin secp256k1_ffi, com.example.secp256k1_ffi.Secp256k1FfiPlugin", e);
    }
  }
}
