// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Future<Uint8List> encryptEcies({
  required List<int> msg,
  required List<int> publicKeyBytes,
}) => RustLib.instance.api.crateApiSimpleEncryptEcies(
  msg: msg,
  publicKeyBytes: publicKeyBytes,
);

Future<Uint8List> decryptEcies({
  required List<int> encryptedMsg,
  required List<int> privateKeyBytes,
}) => RustLib.instance.api.crateApiSimpleDecryptEcies(
  encryptedMsg: encryptedMsg,
  privateKeyBytes: privateKeyBytes,
);

Future<Uint8List> signFrost({
  required List<int> msg,
  required List<int> keyPackageBytes,
  required List<int> nonceBytes,
  required List<int> selfCommitmentBytes,
  required Map<String, Uint8List> statechainCommitmentsBytes,
  Uint8List? adaptorPublicKey,
}) => RustLib.instance.api.crateApiSimpleSignFrost(
  msg: msg,
  keyPackageBytes: keyPackageBytes,
  nonceBytes: nonceBytes,
  selfCommitmentBytes: selfCommitmentBytes,
  statechainCommitmentsBytes: statechainCommitmentsBytes,
  adaptorPublicKey: adaptorPublicKey,
);

Future<Uint8List> aggregateFrost({
  required List<int> msg,
  required Map<String, Uint8List> statechainCommitmentsBytes,
  required List<int> selfCommitmentBytes,
  required Map<String, Uint8List> statechainSignatures,
  required List<int> selfSignature,
  required Map<String, Uint8List> statechainPublicKeys,
  required List<int> selfPublicKey,
  required List<int> verifyingKey,
  Uint8List? adaptorPublicKey,
}) => RustLib.instance.api.crateApiSimpleAggregateFrost(
  msg: msg,
  statechainCommitmentsBytes: statechainCommitmentsBytes,
  selfCommitmentBytes: selfCommitmentBytes,
  statechainSignatures: statechainSignatures,
  selfSignature: selfSignature,
  statechainPublicKeys: statechainPublicKeys,
  selfPublicKey: selfPublicKey,
  verifyingKey: verifyingKey,
  adaptorPublicKey: adaptorPublicKey,
);

Future<DummyTxResult> createDummyTx({
  required String address,
  required BigInt amountSats,
}) => RustLib.instance.api.crateApiSimpleCreateDummyTx(
  address: address,
  amountSats: amountSats,
);

Future<AdaptorSignatureResult> generateAdaptorFromSignature({
  required List<int> signatureBytes,
}) => RustLib.instance.api.crateApiSimpleGenerateAdaptorFromSignature(
  signatureBytes: signatureBytes,
);

Future<Uint8List> generateSignatureFromExistingAdaptor({
  required List<int> signatureBytes,
  required List<int> adaptorPrivateKeyBytes,
}) => RustLib.instance.api.crateApiSimpleGenerateSignatureFromExistingAdaptor(
  signatureBytes: signatureBytes,
  adaptorPrivateKeyBytes: adaptorPrivateKeyBytes,
);

Future<void> validateAdaptorSignature({
  required List<int> pubKey,
  required List<int> hash,
  required List<int> signature,
  required List<int> adaptorPubKey,
}) => RustLib.instance.api.crateApiSimpleValidateAdaptorSignature(
  pubKey: pubKey,
  hash: hash,
  signature: signature,
  adaptorPubKey: adaptorPubKey,
);

Future<Uint8List> applyAdaptorToSignature({
  required List<int> pubKey,
  required List<int> hash,
  required List<int> signature,
  required List<int> adaptorPrivateKey,
}) => RustLib.instance.api.crateApiSimpleApplyAdaptorToSignature(
  pubKey: pubKey,
  hash: hash,
  signature: signature,
  adaptorPrivateKey: adaptorPrivateKey,
);

Future<List<VerifiableSecretShareResult>> splitSecretWithProofs({
  required List<int> secret,
  required BigInt threshold,
  required BigInt numShares,
}) => RustLib.instance.api.crateApiSimpleSplitSecretWithProofs(
  secret: secret,
  threshold: threshold,
  numShares: numShares,
);

Future<Uint8List> recoverSecret({required List<SecretShare> shares}) =>
    RustLib.instance.api.crateApiSimpleRecoverSecret(shares: shares);

/// > **⚠️ IMPORTANT:** Index is not zero based. For index 0, use 1.
Future<void> validateShare({
  required List<int> share,
  required int index,
  required BigInt threshold,
  required List<Uint8List> proofs,
}) => RustLib.instance.api.crateApiSimpleValidateShare(
  share: share,
  index: index,
  threshold: threshold,
  proofs: proofs,
);

Future<NodeTxPairResult> constructNodeTxPair({
  required List<int> parentTxBytes,
  required int vout,
  required String address,
  required int sequence,
  required int directSequence,
  required BigInt feeSats,
}) => RustLib.instance.api.crateApiSimpleConstructNodeTxPair(
  parentTxBytes: parentTxBytes,
  vout: vout,
  address: address,
  sequence: sequence,
  directSequence: directSequence,
  feeSats: feeSats,
);

Future<RefundTxTrioResult> constructRefundTxTrio({
  required List<int> cpfpNodeTxBytes,
  Uint8List? directNodeTxBytes,
  required int vout,
  required List<int> receivingPubkey,
  required String network,
  required int sequence,
  required int directSequence,
  required BigInt feeSats,
}) => RustLib.instance.api.crateApiSimpleConstructRefundTxTrio(
  cpfpNodeTxBytes: cpfpNodeTxBytes,
  directNodeTxBytes: directNodeTxBytes,
  vout: vout,
  receivingPubkey: receivingPubkey,
  network: network,
  sequence: sequence,
  directSequence: directSequence,
  feeSats: feeSats,
);

Future<Uint8List> computeMultiInputSighash({
  required List<int> txBytes,
  required int inputIndex,
  required List<Uint8List> prevOutScripts,
  required Uint64List prevOutValues,
}) => RustLib.instance.api.crateApiSimpleComputeMultiInputSighash(
  txBytes: txBytes,
  inputIndex: inputIndex,
  prevOutScripts: prevOutScripts,
  prevOutValues: prevOutValues,
);

class AdaptorSignatureResult {
  final Uint8List part1;
  final Uint8List part2;

  const AdaptorSignatureResult({required this.part1, required this.part2});

  @override
  int get hashCode => part1.hashCode ^ part2.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AdaptorSignatureResult &&
          runtimeType == other.runtimeType &&
          part1 == other.part1 &&
          part2 == other.part2;
}

class DummyTxResult {
  final Uint8List tx;
  final String txid;

  const DummyTxResult({required this.tx, required this.txid});

  @override
  int get hashCode => tx.hashCode ^ txid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DummyTxResult &&
          runtimeType == other.runtimeType &&
          tx == other.tx &&
          txid == other.txid;
}

class InternalTransactionResult {
  final Uint8List txBytes;
  final Uint8List sighash;

  const InternalTransactionResult({
    required this.txBytes,
    required this.sighash,
  });

  @override
  int get hashCode => txBytes.hashCode ^ sighash.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is InternalTransactionResult &&
          runtimeType == other.runtimeType &&
          txBytes == other.txBytes &&
          sighash == other.sighash;
}

class NodeTxPairResult {
  final InternalTransactionResult cpfp;
  final InternalTransactionResult direct;

  const NodeTxPairResult({required this.cpfp, required this.direct});

  @override
  int get hashCode => cpfp.hashCode ^ direct.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is NodeTxPairResult &&
          runtimeType == other.runtimeType &&
          cpfp == other.cpfp &&
          direct == other.direct;
}

class RefundTxTrioResult {
  final InternalTransactionResult cpfpRefund;
  final InternalTransactionResult? directRefund;
  final InternalTransactionResult directFromCpfpRefund;

  const RefundTxTrioResult({
    required this.cpfpRefund,
    this.directRefund,
    required this.directFromCpfpRefund,
  });

  @override
  int get hashCode =>
      cpfpRefund.hashCode ^
      directRefund.hashCode ^
      directFromCpfpRefund.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RefundTxTrioResult &&
          runtimeType == other.runtimeType &&
          cpfpRefund == other.cpfpRefund &&
          directRefund == other.directRefund &&
          directFromCpfpRefund == other.directFromCpfpRefund;
}

class SecretShare {
  final BigInt threshold;
  final int index;
  final Uint8List share;

  const SecretShare({
    required this.threshold,
    required this.index,
    required this.share,
  });

  @override
  int get hashCode => threshold.hashCode ^ index.hashCode ^ share.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SecretShare &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          index == other.index &&
          share == other.share;
}

class VerifiableSecretShareResult {
  final BigInt threshold;
  final int index;
  final Uint8List share;
  final List<Uint8List> proofs;

  const VerifiableSecretShareResult({
    required this.threshold,
    required this.index,
    required this.share,
    required this.proofs,
  });

  @override
  int get hashCode =>
      threshold.hashCode ^ index.hashCode ^ share.hashCode ^ proofs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VerifiableSecretShareResult &&
          runtimeType == other.runtimeType &&
          threshold == other.threshold &&
          index == other.index &&
          share == other.share &&
          proofs == other.proofs;
}
